name: Update the AT documentation reference

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to link this update to, for example 2022-10'
        required: false
        default: 'undefined'
jobs:
  build_and_preview:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Set ref for the checkout
        if: github.event.inputs.version != 'undefined'
        run: |
          echo "REF_NAME=release/${{ github.event.inputs.version }}" >> $GITHUB_ENV
      - name: checkout analytics-toolbox
        uses: actions/checkout@v3
        with:
          path: ./.checkout/analytics-toolbox
          repository: CartoDB/analytics-toolbox
          submodules: recursive
          token: ${{ secrets.CARTO_GITHUB_TOKEN }}
          ref: ${{ env.REF_NAME }}
      - name: Update docs
        run: 
          ./scripts/update.sh          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Documentation updated automatically for version ${{ github.event.inputs.version }}
          branch: docs/${{ github.event.inputs.version }}
